Add VHDL library support to Xcelium
cocotb/cocotb pull request #2614
Opened 2021-07-07 19:12 UTC by martijnbastiaan

For GHDL/ModelSim/Questa users can specify:

```
VHDL_SOURCES_a = [..]
```

To compile a bunch of VHDL files into a library called `a`. This PR adds support for this feature for Xcelium.

-----------

A couple of remarks:

 * Using `xcelium.d` doesn't feel neat to me, but I haven't found another way _without_ losing support for builtin libraries (ieee/std/synopsys/...)
 * Initializing `xcelium.d` with `xmvhdl -STATUS > /dev/null 2>&1 || true` doesn't feel neat to me either, but again I haven't found another way.
 * For 100% backwards compatibility, we could skip using `xcelium.d` if no `VHDL_SOURCES_*` exists.

2021-07-07 20:14 UTC, cmarqu requested changes

2021-07-07 20:14 UTC, cmarqu commented on cocotb/share/makefiles/simulators/Makefile.xcelium
> +COMPILE_ARGS += -CDSLIB xcelium.d/cds.lib -HDLVAR xcelium.d/hdl.var
```suggestion
COMPILE_ARGS += -cdslib xcelium.d/cds.lib -hdlvar xcelium.d/hdl.var
```
...to stay consistent.

2021-07-07 20:14 UTC, cmarqu commented on cocotb/share/makefiles/simulators/Makefile.xcelium
> +define make_lib
xrun accepts the "-makelib mylibname mysource1.vhd ... -endlib" options which should work. No need for cds.lib.

2021-07-08 08:00 UTC, martijnbastiaan commented
Thanks for the suggestion @cmarqu, that makes things quite a bit neater. Let me know if you have any more comments.

2021-07-09 06:14 UTC, cmarqu commented
Thanks for the quick change. 
The use of `eval` makes me a bit uneasy, but I don't immediately see a way of working around it, other than going the way some other makefiles do it, namely writing out an options file (e.g. `xrun_cocotb.f`) to be loaded. This might have other unforeseen consequences though...
Other opinions?

2021-07-09 06:17 UTC, cmarqu commented on cocotb/share/makefiles/simulators/Makefile.xcelium
> +	$(eval LIBS += -endlib)
```suggestion
	$(eval LIBS += -makelib $(SOURCES_VAR:VHDL_SOURCES_%=%) $($(SOURCES_VAR)) -endlib)
```
I guess reducing the amount of eval calls could be better.

2021-07-09 06:18 UTC, cmarqu commented on tests/test_cases/test_vhdl_libraries/Makefile
>  	@echo "Skipping test since only GHDL and Questa/Modelsim is supported"
```suggestion
	@echo "Skipping test since only GHDL, Questa/Modelsim and Xcelium are supported"
```

2021-07-09 07:44 UTC, themperek approved these changes

2021-07-09 08:19 UTC, martijnbastiaan commented
@cmarqu I kinda tunnel-visioned myself by placing the `LIB` part right before the line that calls the simulator. If I simply move it outside, there's no need for `eval` :)

2021-07-14 14:12 UTC, ktbarrett approved these changes
Seems good to me. If @cmarqu doesn't comment I'm merge tomorrow.

2021-07-14 15:40 UTC, cmarqu approved these changes

2021-07-14 16:49 UTC, merged