Add coverage exclusions
cocotb/cocotb pull request #2624
Opened 2021-07-17 17:04 UTC by ktbarrett

Just for `pass` and `...` statements right now. But that could extend so we have less `# pragma: no cover` comments strewn about.

2021-07-19 12:12 UTC, cmarqu approved these changes

2021-07-19 12:35 UTC, eric-wieser commented
Why is ignoring coverage on `pass` statements a sensible thing to do? Consider:
```
try:
    x = foo()
except:
    pass
return x + y
```
A coverage failure on the `pass` highlights a real missing test that would find a bug

2021-07-19 12:37 UTC, eric-wieser requested changes
I think it's better to use the comment explicitly on a case by case basis rather than trying to guess which coverage exemptions don't matter (ie `pass`).

`...` is probably the exception to that rule since that's only for mypy, right?

2021-07-19 13:33 UTC, ktbarrett commented
Well the intent is to ignore empty function bodies for type stubs and abstract methods, but regexes aren't the greatest in that respect. By convention we could say that `...` is ignored while `pass` is not?

2021-07-19 13:33 UTC, ktbarrett commented on setup.cfg
> +    pass
```suggestion
```

2021-07-21 23:15 UTC, eric-wieser approved these changes
Thanks - if you can add a comment explaining why ... is there (for overload), that would be great

2021-07-22 00:05 UTC, merged

2021-07-22 16:50 UTC, ktbarrett commented
I think I merged this just a little too early... https://github.com/nedbat/coveragepy/issues/1131#issuecomment-884982574. Apparently there is a soon-to-be-documented feature where decorators in `exclude_lines` skip the entire function that are decorated.