Links added for Open Source simulators
cocotb/cocotb pull request #2794
Opened 2021-11-30 07:32 UTC by ALI11-2000

For Issue #1984, links are added for about us and installation instructions for Icarus Verilog, Verilator and GHDL.

2021-11-30 20:18 UTC, cmarqu commented
Thanks for the pull request, @ALI11-2000!
I am a bit undecided about whether we should add potentially unstable links though - they would live on in released documentation.
What do other maintainers think?

It would be nice if we had a "jumping board"/forwarder in between that we could easily adjust if needed. Or maybe a link to a cocotb Wiki site?

2021-11-30 20:37 UTC, ktbarrett commented
I agree it would be nice to have an easy to update link, like a pointer to pointer, to keep in the Wiki. I'm webstupid, not sure how to accomplish that. If that's not easily possible, I'm fine with bringing this in. I'd probably reword it slightly "You can find instructions on installing iverilog 'here'." or similar.

2021-12-01 06:28 UTC, imphil commented
I wouldn't worry about links becoming unstable. It's convenient if the links work, but not worse than today if they don't.

2021-12-01 06:32 UTC, imphil commented on documentation/source/simulator_support.rst
> +    This section requires `installation <https://iverilog.fandom.com/wiki/Installation_Guide>`_ of `Icarus Verilog <http://iverilog.icarus.com/>`_.
"This section" sounds a bit odd to me: it's not this section of text that needs Icarus Verilog, but running a design with it. How about (something like) "A working installation of Icarus Verilog is required. Refer to their documentation for installation instructions."

2021-12-01 07:43 UTC, ALI11-2000 commented
How about adding a sub-section for open-source simulators in the Wiki (in [non-cocotb but related](https://github.com/cocotb/cocotb/wiki/Further-Resources#non-cocotb-but-related) section ) page which would contain the links for the installation instructions of those simulators and the documentation can refer to that section?

2021-12-01 14:51 UTC, ktbarrett approved these changes
On second thought I don't think we need to worry about invalid links. Ideally if those FOSS simulators move their documentation, they should set up redirects properly. Thanks for updating the note wording, and thanks for doing this @ALI11-2000!

2021-12-01 20:33 UTC, cmarqu requested changes

2021-12-01 20:33 UTC, cmarqu commented on documentation/source/simulator_support.rst
> +    A working installation of `Verilator <https://www.veripool.org/verilator/>`_ is required. You can find installation instructions can  `here <https://verilator.org/guide/latest/install.html>`_.
```suggestion
    A working installation of `Verilator <https://www.veripool.org/verilator/>`_ is required.
    You can find installation instructions `here <https://verilator.org/guide/latest/install.html>`_.
```

2021-12-01 20:33 UTC, cmarqu commented on documentation/source/simulator_support.rst
> +    A working installation of `GHDL <http://ghdl.free.fr/>`_ is required. You can find installation intructions `here <http://ghdl.free.fr/site/pmwiki.php?n=Main.Installation>`_.
```suggestion
    A working installation of `GHDL <https://ghdl.github.io/>`_ is required. You can find installation instructions `here <https://ghdl.github.io/ghdl/getting.html>`_.
```

2021-12-01 20:33 UTC, cmarqu commented on documentation/source/simulator_support.rst
> +
```suggestion
```

2021-12-01 20:33 UTC, cmarqu commented on documentation/source/simulator_support.rst
> +
```suggestion
```

2021-12-01 20:33 UTC, cmarqu commented on documentation/source/simulator_support.rst
> +    A working installation of `Icarus Verilog <http://iverilog.icarus.com/>`_ is required. You can find installation instructions `here <https://iverilog.fandom.com/wiki/Installation_Guide>`_.
```suggestion
    A working installation of `Icarus Verilog <http://iverilog.icarus.com/>`_ is required.
    You can find installation instructions `here <https://iverilog.fandom.com/wiki/Installation_Guide>`_.
```

2021-12-02 03:30 UTC, ALI11-2000 reviewed
Updated the link as the previously suggested one was not working.

2021-12-02 17:51 UTC, cmarqu approved these changes

2021-12-02 17:51 UTC, merged

2021-12-02 17:56 UTC, cmarqu commented
@ALI11-2000 Thank you!