Change to nox
cocotb/cocotb pull request #2881
Opened 2022-02-28 05:18 UTC by ktbarrett

This commit removes the tox.ini, changes the CI to use nox instead, and update contributing instructions to reference nox and pre-commit.

2022-02-28 21:42 UTC, cmarqu requested changes

2022-02-28 21:42 UTC, cmarqu commented on CONTRIBUTING.md
> +and [pre-commit](), to check your changes before committing them.
```suggestion
and [pre-commit](https://pre-commit.com/), to check your changes before committing them.
```

2022-02-28 21:42 UTC, cmarqu commented on CONTRIBUTING.md
> +When committing pre-commit's hook will run, checking your changes for formatting, code smells, etc.
```suggestion
When committing, pre-commit's hook will run, checking your changes for formatting, code smells, etc.
```

2022-03-01 22:35 UTC, marlonjames commented
You need to point private CI at your branch in the other repo.
Looks like you should add a `ref` to the `repository` in `.azp-private.yml` per https://docs.microsoft.com/en-us/azure/devops/pipelines/process/resources?view=azure-devops&tabs=schema#define-a-repositories-resource

2022-03-01 22:40 UTC, ktbarrett commented
@marlonjames I figured we would just update the private CI first so there isn't a back-and-forth of pointing to different branches.

2022-03-04 20:00 UTC, cmarqu approved these changes

2022-03-06 02:52 UTC, merged