Fix `test_long_log_msg`
cocotb/cocotb pull request #2973
Opened 2022-05-17 03:26 UTC by ktbarrett

From https://github.com/cocotb/cocotb/pull/2924#issuecomment-1128245463.

2022-05-17 03:53 UTC, ktbarrett commented
Apparently Window's version of `vsnprintf` when encountering a potential buffer overflow returns `-1` instead of the number of characters which would have been written, violating the C99 standard. This affects code compiled with MSVC and mingw, apparently is fixed in UCRT, and may or may not work in msys/cygwin. Guess I'll just have to use a dumber algorithm...

2022-05-17 04:06 UTC, ktbarrett commented
The new fix is now only slower and dumber on Windows and should continue working like it did previously on other OSes.

2022-05-17 14:19 UTC, marlonjames commented on cocotb/share/lib/gpi_log/gpi_logging.cpp
> +        va_copy(argp_copy_again, argp);
```suggestion
        va_copy(argp_copy_again, argp_copy);
```
`argp` is already used at this point.

2022-05-17 14:30 UTC, ktbarrett commented
Something is not right... `cat`ing out the error log we get [this](https://github.com/cocotb/cocotb/runs/6464420830?check_suite_focus=true#step:19:2260). The error message can only be `Error constructing log message` followed by `1` or `2`, a colon, then the error code. That's not what we are seeing, so I'm not sure where this is coming from? Maybe I'm just loosing my mind.

2022-05-17 14:38 UTC, ktbarrett commented
Ohnonono, we aren't actually testing cocotb on Windows, the build fails and it just pulls down cocotb 1.6.2 from pypi. https://github.com/cocotb/cocotb/runs/6464420830?check_suite_focus=true#step:16:28

2022-05-17 15:25 UTC, marlonjames commented
Whatever we do in `gpi_logging.cpp` we need to copy over to `py_gpi_logging.cpp` because that is the actual handler.

2022-05-18 08:00 UTC, imphil commented
Maybe a stupid question: can we link against/use UCRT and simply get the C99-conforming vnsprintf() function? (Even msys seems to support UCRT, from my reading of https://www.msys2.org/docs/environments/ -- and we primarily care about MSVC anyways.)

2022-05-18 14:41 UTC, imphil commented
Just to be clear: I'd be interested in exploring the use of UCRT. But that's optional, the approach in this PR is clearly sufficient for now and gets us past this failure. Let me know @ktbarrett when you'd like a review to happen.

2022-05-18 15:13 UTC, ktbarrett commented
@imphil The mingw compiler test still fails on master, I have no idea if this fix works or not.

2022-05-18 15:58 UTC, marlonjames commented
This might have some info: https://mingwpy.github.io/ucrt.html

2022-06-21 20:11 UTC, ktbarrett commented
This PR is now good to come in despite mingw compiler not working because we no longer support that compiler on Windows, right?

2022-06-22 20:51 UTC, imphil commented
Yeah, let's confirm that by rebasing this PR on top of the latest master.

2022-06-24 15:50 UTC, marlonjames requested changes
The test is still disabled in the Makefile.

It's not run in the windows CI run (or any CI run):
https://github.com/cocotb/cocotb/runs/7042194080?check_suite_focus=true#step:17:3117

2022-06-27 14:34 UTC, ktbarrett commented
Codecov is all kinds of screwed up on this PR, but the change should be complete.

2022-06-27 14:49 UTC, ktbarrett commented on cocotb/share/lib/gpi_log/gpi_logging.cpp
> +        // that would be written, even on Windows...
Added a link to the MSDN documentation which has more information.

2022-07-02 00:08 UTC, marlonjames approved these changes

2022-07-02 00:14 UTC, merged