[Vpi] Allow using unpacked struct as a signal on sim module
cocotb/cocotb pull request #3608
Opened 2023-12-27 00:09 UTC by AndrewNolte

The purpose of this is to be able to set/get a struct's entire value, rather than just its individual signals, which in turn will allow for more shared user code between verilator and the other environments. I haven't put any handle.py changes on here, because I'm not sure how we'd want to implement that.

A vpi struct incorporates aspects of both non-hierarchy and hierarchy objects. I think it's most similar to an array in this sense, but has the added trouble of having potential namespace conflicts (a struct containing something named 'value'). There's also the trouble of writing to both the overall struct and the individual components, but I'm assuming the vpi layer already has an answer to this.

2024-01-11 18:29 UTC, AndrewNolte commented
I realized when running this that doing
```
make -C tests/test_cases/test_struct SIM=xcelium
make -C tests/test_cases/test_struct SIM=verilator
```
in sequence causes the verilator one to not run and exit early, any idea why this might be the case? I have to make clean before I can run verilator

2024-01-23 14:49 UTC, AndrewNolte commented
Can I get a look at this @marlonjames @ktbarrett. I'm not sure why it's tripping up on vhdl runs

2024-01-23 20:21 UTC, ktbarrett commented
I'll try to do this tonight. Otherwise it might be a while.

2024-01-24 19:29 UTC, AndrewNolte commented
It looks like vhdl sims actually seg fault when trying to call get_signal_val_binstr, which is why they failed even though expect_fail was set to true. And the verilog ones rn are because of the logicarray change, I'll fix those rq

2024-02-06 15:49 UTC, ktbarrett commented
Just changing structs to arrays is not the right answer here. I'm actually really surprised that the regression passes with this change. Clearly not enough testing is being done. What's needed is a new type that supports both accessing fields and setting the whole value.

I don't know what happens when you attempt to set the full value on something that isn't a packed struct, or if most simulators even support differentiating packed vs unpacked structs.

2024-02-06 17:16 UTC, AndrewNolte commented
It's essentially just adding the signal methods to the gpi handle, whereas before it didn't have these. Changing handle.py to allow both hierarchy and signal will be the tricky part

2024-02-07 00:51 UTC, marlonjames commented
`sample_module.inout_if` happens to be a packed struct here, but unpacked structures and unpacked unions cannot be set in their entirety with `vpi_put_value()`.

This type of feature would at minimum require getting `vpi_get(vpiPacked)` to differentiate, and I agree with Kaleb on developing a new type for interfacing to it.

2024-03-01 16:01 UTC, ktbarrett commented
Actually now that I've been thinking about this. I think this might be a good idea. Indexing into packed objects, whether that's packed arrays, or packed structs, etc. is not kosher, at least conceptually. I'm now more surprised that what we currently have works.

We do need a new type for packed objects that aren't single-dimension packed arrays.

2024-03-07 16:39 UTC, AndrewNolte commented
"What's needed is a new type that supports both accessing fields and setting the whole value." - so only VpiSignal provide special extra methods, VpiObjHdl does not. Everything for accessing fields is just operating on the raw vpi handle, so our check for that is simply 'does the vpi throw an error' and relying on handle.py to call it on valid objects.

So I can make a VpiStructObjHdl that just extends VpiSignalObjHdl, but it'll add nothing. And I'll add the vpiPacked check as well. It would be nice to also have it extend VpiObjHdl to get defname and deffile, but then we'd have multiple inheritance

2024-03-12 17:01 UTC, ktbarrett commented
I'm still trying to figure out a holistic approach to this.

In my mind:
1. You can't index into packed objects.
2. Packed objects are discovered as single GPI_PACKED objects.
3. This gets mapped to a `LogicObject` or similar which cannot be indexed.
4. You should be able to query the structure of that object (`[0:2][0:2]packed_struct_t[7:0]`, etc.).
5. The Python type we return from `.value` of such objects should use the structure definition to support indexing and updated the value, but getting and setting the value on the handle only happens whole packed object at a time.

I know this is going to require both C++ and Python changes, but I'm uncertain to what extent. Also I'm uncertain if point 4 is even possible.

2024-03-12 21:21 UTC, AndrewNolte commented
Do many simulators support the type spec? For xcelium (and seemingly other sims) it just treats them as unpacked. I think just having this for now supports the old way via an explicit type change. I was originally going to support both .value and child handle access, but with the latest rebase there were some method conflicts between LogicObject and HierarchyObject, so I thought it best to default to the proper way for Packed Structs. (__len__) especially would be confusing

And again, what cpp changes need to be made if we're not inspecting the type spec? The object hierarchy was implemented as methods on GpiObjHdl and VpiImpl, not VpiObjHdl, so it works just fine.

2024-04-21 22:28 UTC, ktbarrett commented
So uhhh... yeah I definitely want to go back to the original implementation on this. Let's just remove support for now and try to realize #3857 sooner rather than later.

2024-04-21 22:29 UTC, ktbarrett requested changes
So uhhh... yeah I definitely want to go back to the original implementation on this. Let's just remove support for now and try to realize #3857 sooner rather than later.

2024-04-29 18:38 UTC, ktbarrett requested changes

2024-04-29 18:38 UTC, ktbarrett commented on tests/test_cases/test_struct/test_struct.py
> +    ),  # verilator already treats packed structs as logic arrays
Why would we skip this then? Shouldn't it pass?

2024-04-29 18:38 UTC, ktbarrett commented on tests/test_cases/test_iteration_mixedlang/test_iteration.py
>          pass_total = 1332
```suggestion
        pass_total = 1276
```
A difference of 56. Does that sound right?

2024-05-01 02:31 UTC, ktbarrett approved these changes

2024-05-08 18:03 UTC, cmarqu commented on tests/test_cases/test_struct/test_struct.py
> +    # use value or value to access signal
```suggestion
    # use value to access signal
```
?

2024-05-20 02:42 UTC, ktbarrett commented on tests/test_cases/test_struct/test_struct.py
> +    cocotb.log.info("dut.my_struct.value=%s", dut.my_struct.value)
```suggestion
```

2024-05-20 02:49 UTC, ktbarrett commented
@cocotb/maintainers Considering I plan on reintroducing the indexing in a future commit, is this good?

2024-05-22 17:11 UTC, merged